CHANGELOG.md
README.md
__tests__/index.js
index.js
package.json

The align property on the table AST node was an array, which I didn't realize before. Not actually an mdast issue.

GFM Aligned Column functionality

---

CHANGELOG.md
README.md
__tests__/index.js
index.js
package.json

mdast 2.x -> remark 3.x, prep for 1.2.0

---

CHANGELOG.md
__tests__/index.js
jest.preprocessor.js
package.json

Updated internals, no user-facing changes. Now testing against React 15.x

Update dev deps

---

package.json

chore(package): update react to version 15.0.2

---

README.md
index.js
index.spec.js

Inline HTML handling, function signature changes for 4.0

---

README.md
index.js
index.spec.js

See the README for updated usage instructions.

[Breaking Change] Default export is now a React HOC

---

index.js
package.json

This will stop other packages using this throwing errors.

Upgrade to React 15.5.4 (and use prop-types package)

---

.travis.yml
package.json
yarn.lock

1. Will fail the CI if the library grows too big.
2. Run npm run size -- --why to run Webpack Bundle Analyzer.

Add size-limit

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

This fixes an extra layout div being added when it wasn't needed.

trim existing newlines when in block mode

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

Fixes bad matching that would occur if an element occurs more than once in an HTML sequence.
(issue: #125)

fixes greedy html capture pattern

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

fix handling of nested HTML tags of the same type

---

README.md
__snapshots__/index.spec.js.snap
index.js
index.spec.js

some wrapper adjustments, add forceInline and forceBlock parsing options

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

fix #136 and optimize the block html regex

---

README.md
__snapshots__/index.spec.js.snap
index.js
index.spec.js

jsx handling adjustments

---

index.js

it does introduce a bit of extra transpiled code, but not enough to matter
closes #146

go back to using proper esm imports

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

handle links with URLs in the link text

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

don't process the inside of style, script blocks

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

Need to be more careful about ensuring the first tag character is an ASCII letter when detecting HTML blocks.
Closes #180

fix for #180

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

improvements to inline syntax parsing for bold, emphasis, and strikethrough

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

fix regex perf issue with emphasis and bolding detectors

---

index.compiler.spec.js
index.js
package.json

graceful fallback for missing footnotes

---

index.compiler.spec.js
index.js

adjust trim when generating table cells

---

index.compiler.spec.js
index.js
package.json

Fix HTML multiline comments bug (#246)

---

index.compiler.spec.tsx
index.tsx

remove redundant HTML comment removal, do not strip inside code blocks

---

.github/workflows/codeql-analysis.yml
.github/workflows/test.yml
index.compiler.spec.tsx
index.tsx

fix: a space is required between id block and url for references

---

index.compiler.spec.tsx
index.tsx

refactor: simplify image+link regexes, allow data image URLs

---

index.compiler.spec.tsx
index.tsx

fix: improve link detection regex

---

README.md
index.compiler.spec.tsx
index.tsx

This is an update to the PR here https://github.com/probablyup/markdown-to-jsx/pull/379/files

#379 - Allow more custom HTML character codes

---

index.compiler.spec.tsx
index.tsx

fix: gracefully handle missing image references
