__tests__/index.js
index.js

Automatically remove the root <div> wrapper for singular children, tight list handling

---

index.js
index.spec.js

The compiler should now handle things like:
```html
<time><span>**Foo**</span></time>
```

[Experimental] Coalesce/parse nested inline tags

---

index.js
index.spec.js

This Markdown
```markdown
Text and <code>**code**</code>
```
renders with this error:
```
warning.js:36 Warning: validateDOMNesting(...): <pre> cannot appear as a descendant of <p>. See Markdown > p > ... > pre.
```

Fix rendering of inline code tags

---

index.js
index.spec.js

Also made a change to omit interim wrappers where possible in
situations where dangerouslySetInnerHTML is unavoidable.
fixes #101

fix: handle self-closing HTML inside parseable HTML

---

package.json
yarn.lock

Fixes #104.
Picture proof that prepublish script is run on install but does not execute `npm run es5`:

Replace prepublishOnly script with in-publish package

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

partially fixes #153 
not 100% happy with this at the moment, as it technically fixes an edge case and introduces a new one (though a less frequent one)

workaround for parsing block html inside arbitrary html

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

Even with regex and comments supporting whitespaces between attributes and values (`<tag key = val />`), the code itself does not account for these spaces and includes them into final strings generating inconsistent parsing like `"foo` instead of `foo` or ` class` instead of `class`...
I added very lightweight change to `trim()` leading and trailing spaces if any.
See #161 
Plus I wrote test cases to prevent any future regression.

Support spaces between equal sign for html attributes

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

fix block-level syntax inference inside arbitrary HTML

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

pass along additional props supplied to the Markdown component

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

should close #170 
could you check this out and confirm the fix @michaelryancaputo?

adjust HTML capture regex

---

__snapshots__/index.spec.js.snap
index.js
index.spec.js

builds on top of the fix in https://github.com/probablyup/markdown-to-jsx/pull/175

handle nested HTML tags of the same type with attributes

---

.eslintrc.json
.prettierrc
__snapshots__/index.spec.js.snap
index.js
index.spec.js
package.json
yarn.lock

Revise inner HTML trimming strategy to avoid false-positive paragraph tag injection.
Closes #181

Reduce false-positive paragraph detection inside arbitrary HTML blocks

---

README.md
__snapshots__/index.spec.js.snap
index.js
index.spec.js

make slugify function configurable

---

index.compiler.spec.js
index.js

We wanted to pass a prop `title` down but it gets sucked up by the parser somehow.
With this change applied it is working.
closes #238

allow to override title property on link parsing

---

index.compiler.spec.js
index.js

Right now, you can inject `script` and `style` tags by using uppercase letters, e.g. `<SCRIPT>alert('hi')</SCRIPT>`. This PR converts tag names to lowercase before evaluating against the blacklist.

[XSS] Ignore case of blacklisted HTML elements

---

README.md
index.js

add new option namedCodesToUnicode (#236)

---

index.compiler.spec.js
index.js
yarn.lock

Previously links like `<a href="javascript:alert('hi')">Foo</a>` were passed through unsanitized while `[javascript:alert('hi')](Foo)` was sanitized. This change makes both sanitized, and also escapes any other `href` attributes.
This fixes #239. This also includes a change to prevent element name case from subverting the HTML element blacklist.

Sanitize `href` values

---

index.compiler.spec.js
index.js

Should fix #258
A port of https://github.com/Khan/simple-markdown/commit/f32a628401745787a2a199a5d3bde1efced4d6d5
to markdown-to-jsx.
Previously, tables were parsed using String.prototype.split on pipe
(`|`) characters.
This PR changes table parsing to use a full parse() call, using a
new `tableSeparator` rule to match tableSeparators. Because
`tableSeparator` is now a rule, the `escapedText` rule can handle
escaped pipes within the table, and the `codeInline` rule can handle
inline code with pipes in it.
Test plan:
Added tests to index.compiler.spec.js

Fix #258: Allow escaping pipes within tables

---

index.compiler.spec.js
index.js

I found out if to pass to compiler string with consecutive `\n` in the middle of the text, then this replace doesn't work
```
`${input.replace(TRIM_NEWLINES_AND_TRAILING_WHITESPACE_R, '')}\n\n`,
```
There is an infinite loading. It happens only when the sequence of `\n` is longer than 25-30 symbols.
This bug was implemented in this commit https://github.com/probablyup/markdown-to-jsx/commit/bef82a5fa3f84fddb16b423f95f4930dfcbcf8e3 
I suppose that group inside the group in regex works very slow, that is why there is an infinite loading.
So in this PR I added the test of this case and simplified regex for TRIM_NEWLINES_AND_TRAILING_WHITESPACE_R

Fix TRIM_NEWLINES_AND_TRAILING_WHITESPACE_R regex bug

---

README.md
index.compiler.spec.js
index.js
package.json

Taking my cue from #225, I went with a probably-too-naive approach but I figured it'd be a starting point.

Optionally disable HTML parsing

---

index.js

Fixes a bug in which empty style attributes result in unrecoverable JSX failures. For example:
```html
<div style>Foo</div>
```
Would result in the following console error:
```
Uncaught Invariant Violation: The `style` prop expects a
mapping from style properties to values, not a string.
For example, style={{marginRight: spacing + 'em'}} when
using JSX.
```
and the React JSX failing to render.
The problem is that empty properties are rendered as boolean `true` by default. This is consistent with HTML/React syntax interop expectations for most properties but not `style`, which expects an `Object` value in React-land.
Since an empty `style` attribute is semantically meaningless (where HTML is concerned) we can simply skip over this property.

Fix: Support empty style attribute

---

index.compiler.spec.js
index.js

Fixes #306 : I believe this fixes https://www.npmjs.com/advisories/1219 if
`options.disableParsingRawHTML` is set.
NOTE: This does not handle script elements, etc., that may be rendered
when `options.disableParsingRawHTML` is not enabled. We might be able to
use something like [`dompurify`](https://github.com/cure53/DOMPurify) to
solve that case?
According to https://owasp.org/www-community/xss-filter-evasion-cheatsheet ,
the dangerous `javascript:` protocol can contain some whitespace
characters and still be vulnerable, and sometimes when used in
conjunction with images, some other special characters like ` or <
before the javascript: protocol can also leave a url vulnerable.
This change re-adds the sanitiation logic removed in 9c6c782c , and also
adds the vbscript/data handling from …

Fix sanitizeUrl vbscript/data xss

---

index.compiler.spec.tsx
index.tsx
package.json
yarn.lock

This is a work-in-progress, and I'd like some feedback. The functionality works, but there aren't any tests yet.
The `wrapper` option allows for providing a React component or element name that'll be used to create the outermost wrapper around the rendered content, replacing the `div` or `span` that would be used otherwise. 
```jsx
const markdownContent = "# Hello, world!"
const Container = props => <section className="container" {...props} />
const Component = () => (
<Markdown options={{ wrapper: Container }}>{markdownContent}</Markdown>
)
```
```html
<section class="container">
<h1>Hello, world!</h1>
</section>
```
This also works with the `compiler` directly.
The `renderArray` option expects a boolean. When `true`, no wrapper will be used at all and an array of elements will be …

Add support for `wrapper` option

---

index.tsx

Currently providing overrides using intrinsic elements like
```tsx
p: {
component: 'p',
props: {
className: 'inline',
},
},
```
will result in a typescript error of `Type 'string' is not assignable to type 'ComponentType<any>'.`, even though it works
`React.ElementType` includes intrinsic elements and I believe is more appropriate here

typescript typing: use React.ElementType rather than React.ComponentType

---

README.md

Here's a reasonable initial draft of the documentation on these new options. Feel free to wordsmith, revise, or reword, or ask for changes.
I tried following your formatting, generally, but some of these things get kind of tricky to convey in a README without getting very into the weeds with React component representations and such, and I don't know that I did a great job. Also, prettier kept making things worse, so I saved without formatting so there's probably at least one formatting goof.

Document `wrapper` and `forceWrapper` options

---

index.tsx

This PR adds null to the possible types for `wrapper`. This type is already described in the documentation, so does not require any further changes.
Addresses #375

#375 - Add null to possible types for wrapper.

---

README.md

[`preact-compat` is specifically for Preact v8 and prior](https://github.com/preactjs/preact-compat/#preact-compat), which isn't very relevant today. `preact/compat` is where compat lives in v10.

docs: Correcting Preact instructions

---

index.compiler.spec.tsx
index.component.spec.tsx
index.tsx
package.json
site.tsx
tsconfig.json
unquote.d.ts
yarn.lock

For reasons outlined in #425, disable `esModuleInterop` and update all relevant imports.
When I disabled `esModuleInterop`, microbundle (rollup) started giving a warning "cannot call a namespace" regarding `unquote`. It turns out [the implementation of unquote](https://github.com/lakenen/node-unquote/blob/master/index.js) is super simple and not even entirely correct (doesn't verify quotes are symmetric), so I removed the dependency and added a local implementation. (This would also be doable in 2 lines with regex `/^(['"])(.*)\1$/` but it will be a little slower--not sure how much it matters here.)
Fixes #425

Disable esModuleInterop and remove unquote dependency

---

README.md

Nothing much to explain here,
The unescaped tilde in line 547 was making the codeblock that started at 543 to end at 547 instead of 549.

Escaped an unescaped tilde.

---

package.json

This is required to make `moduleResolution: NodeNext` work.
Also requires https://github.com/probablyup/markdown-to-jsx/pull/414

chore: add types to exports

---

index.compiler.spec.tsx
index.tsx

Allows HTML character codes starting with a capital letter to be replaced.
https://github.com/probablyup/markdown-to-jsx/issues/447

feat(compiler): allow replacing of special capital html characters

---

index.tsx

[Catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html) in the `BREAK_THEMATIC_R` regex causes parsing to hang on non-matching input with repeating asterisks like this:
```
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
SOME TEXT
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
```
or even just:
```
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
```
This minor regex change resolves that issue without changing the matched pattern or capture group.

Resolve issue with catastrophic backtracking regex

---

index.compiler.spec.tsx
index.tsx

This is a newer syntax used in some tools like Quill, Obsidian, etc that will ideally be added to CommonMark in the near future.
Fixes #470

feat: add support for "mark" syntax `==text==`

---

index.compiler.spec.tsx
index.tsx

This fixes #488. The issue I found was that when parsing HTML within a markdown table row, if there are nested HTML elements, then when we enter the `parseBlock` function and set `state._inline` to `false`, it prevents any rules using `inlineRegex` or `simpleInlineRegex` when we move on to process other cells in the table. I also added a very basic test for processing HTML within a table row because I didn't see one there. Interested to hear your feedback on this!

fix: correctly parse markdown inside of a table row when a preceding column has nested HTML elements

---

package.json

Closes #498
Fixes #495
This would fix https://github.com/probablyup/markdown-to-jsx/issues/495. This PR specifically is attempting to retry build tests for https://github.com/probablyup/markdown-to-jsx/pull/498 with most-recent code base, as well as updating the tests run in `package.json` relating to `size-limit` and `npm run size`. 
The issues with https://github.com/probablyup/markdown-to-jsx/pull/498 are solely related to the github action not being able to find index.js. It looks like changing `type` to `module` affects the build command (`npm run build`), such that `index.js` is no longer output, but `index.cjs` (for common) and `index.module.js` (for ES) are output, which in turn affects the `size-limit` config in `package.json` (since the output file `index.js` that the test--`npm …

fix: Update package.json for "type": "module" with updated `size-limit` tests for `index.cjs` and `index.module.js` (replacing `index.js`)

---

index.compiler.spec.tsx
index.tsx

Updated regex to support brackets inside the brackets.
Fixes #514

Brackets in link text

---

index.compiler.spec.tsx
index.tsx

Multiline footnotes

---

.changeset/fast-months-play.md
index.compiler.spec.tsx
index.tsx

fix: handle newlines inside HTML tag brackets

---

.changeset/strange-planets-buy.md
index.compiler.spec.tsx
index.tsx

Currently, if we have consecutive blockquotes, they are rendered as one:
**Input**
```md
> Block A.1
> Block A.2
> Block B.1
```
**Output**
```html
<blockquote>
<p>Block A.1</p>
<p>Block A.2</p>
<p>Block.B.1</p>
</blockquote>
```
This is not compliant with the [GFM spec](https://github.github.com/gfm/#block-quotes) which states that we should create consecutive blocks if there is a blank line between them
---
This PR solves that by tweaking the `BLOCKQUOTE_R` regex and adding relevant tests. Basically, we use a lookahead to match everything until we hit at least two `\n`.

fix: consecutive blockquotes blocks

---

.changeset/eighty-bees-think.md
index.compiler.spec.tsx
index.tsx

fix: false detection of nested list due to bad lookback cache

---

.changeset/sharp-lobsters-turn.md
index.compiler.spec.tsx
index.tsx

closes #597
closes #582
Issue was due to script and style tags (elements contained in DO_NOT_PROCESS_HTML_ELEMENTS list) which produces undefined children when parsed. So when text is empty render function will try to render with undefined children which will throw the error.

fix: handle render of empty noInnerParse html nodes like script and style tag #597

---

.changeset/wicked-radios-tap.md
README.md
index.compiler.spec.tsx
index.tsx
package.json

feat: add option to disable autolinking

---

index.tsx

Without explicitly setting the return type and using React 17 types, TS infers JSX.Element instead of React.JSX.Element. Setting it explicitly ensures the return type is React.JSX.Element.

Set compiler return type to React.JSX.Element

---

.changeset/dirty-lies-pump.md
index.compiler.spec.tsx
index.tsx
package.json
yarn.lock

Handle spaces in text as a stop token to improve processing, also adapt paragraph detection to exclude non-atx compliant headings if that option is enabled.
Fixes #680

improve text processing chunking strategy & atx headline selectivity when detecting block syntax

---

.changeset/gentle-numbers-trade.md
index.compiler.spec.tsx
index.tsx

Fixes the issue where link text containing multiple nested brackets is not parsed correctly.
**Before**: `[title[bracket1][bracket2]](url)` fails to parse as a link
**After**: `[title[bracket1][bracket2]](url)` correctly parses as a link
The issue was caused by two factors:
1. The original `LINK_INSIDE` regex pattern couldn't handle nested brackets
2. Rule priority conflict between `link` and `refLink` parsers
Solution Approach
1. **Regex Enhancement**: Updated pattern from `(?:\\[[^\\]]*\\]|[^\\[\\]]|\\](?=[^\\[]*\\]))*` to `(?:\\[[^\\[\\]]*(?:\\[[^\\[\\]]*\\][^\\[\\]]*)*\\]|[^\\[\\]])*`
2. **Rule Conflict Resolution**: Modified `refLink._qualify` to `(source) => source[0] === '[' && source.indexOf('](') === -1` to exclude inline links
3. **Performance Optimization**: Used direct array …

Fix: Handle multiple nested brackets in link text
